"""Added a author_name column to PostModel.

Revision ID: 472f0797f529
Revises: 8106136d1878
Create Date: 2023-03-12 00:24:20.353796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f0797f529'
down_revision = '8106136d1878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=255), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('first',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
